//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("SlSvcUtil", "5.0.61118.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework")]
public partial class ExceptionContext
{
    
    private ExceptionCategory categoryField;
    
    private bool categoryFieldSpecified;
    
    private string codeField;
    
    private string detailField;
    
    private string idField;
    
    private string messageField;
    
    private string traceField;
    
    private string transactionIDField;
    
    private System.DateTime triggerTimeField;
    
    private bool triggerTimeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ExceptionCategory Category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CategorySpecified
    {
        get
        {
            return this.categoryFieldSpecified;
        }
        set
        {
            this.categoryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string Detail
    {
        get
        {
            return this.detailField;
        }
        set
        {
            this.detailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
    public string Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
    public string Trace
    {
        get
        {
            return this.traceField;
        }
        set
        {
            this.traceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public System.DateTime TriggerTime
    {
        get
        {
            return this.triggerTimeField;
        }
        set
        {
            this.triggerTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TriggerTimeSpecified
    {
        get
        {
            return this.triggerTimeFieldSpecified;
        }
        set
        {
            this.triggerTimeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("SlSvcUtil", "5.0.61118.0")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework")]
public enum ExceptionCategory
{
    
    /// <remarks/>
    BusinessError,
    
    /// <remarks/>
    IdentifiedException,
    
    /// <remarks/>
    UnidentifiedException,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("SlSvcUtil", "5.0.61118.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework.Business")]
public partial class BusinessContext
{
    
    private string bizServiceCodeField;
    
    private bool byPassDataIntegrityCheckField;
    
    private bool byPassDataIntegrityCheckFieldSpecified;
    
    private string clientCodeField;
    
    private string institutionCodeField;
    
    private string locationIPAddressField;
    
    private string locationMachineNameField;
    
    private string loginAccountIDField;
    
    private string loginIDField;
    
    private string sessionIDField;
    
    private string transactionIDField;
    
    private string userNameField;
    
    private string userProfileIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string BizServiceCode
    {
        get
        {
            return this.bizServiceCodeField;
        }
        set
        {
            this.bizServiceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool ByPassDataIntegrityCheck
    {
        get
        {
            return this.byPassDataIntegrityCheckField;
        }
        set
        {
            this.byPassDataIntegrityCheckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ByPassDataIntegrityCheckSpecified
    {
        get
        {
            return this.byPassDataIntegrityCheckFieldSpecified;
        }
        set
        {
            this.byPassDataIntegrityCheckFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string ClientCode
    {
        get
        {
            return this.clientCodeField;
        }
        set
        {
            this.clientCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string InstitutionCode
    {
        get
        {
            return this.institutionCodeField;
        }
        set
        {
            this.institutionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
    public string LocationIPAddress
    {
        get
        {
            return this.locationIPAddressField;
        }
        set
        {
            this.locationIPAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
    public string LocationMachineName
    {
        get
        {
            return this.locationMachineNameField;
        }
        set
        {
            this.locationMachineNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string LoginAccountID
    {
        get
        {
            return this.loginAccountIDField;
        }
        set
        {
            this.loginAccountIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
    public string LoginID
    {
        get
        {
            return this.loginIDField;
        }
        set
        {
            this.loginIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
    public string SessionID
    {
        get
        {
            return this.sessionIDField;
        }
        set
        {
            this.sessionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
    public string UserName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string UserProfileID
    {
        get
        {
            return this.userProfileIDField;
        }
        set
        {
            this.userProfileIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("SlSvcUtil", "5.0.61118.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework.Business")]
public partial class BusinessObject
{
    
    private ArrayOfXElement dataField;
    
    private byte[] dataCompressedField;
    
    private bool isDataCompressedField;
    
    private bool isDataCompressedFieldSpecified;
    
    private ArrayOfXElement parameterField;
    
    private bool performCompressionField;
    
    private bool performCompressionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public ArrayOfXElement Data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=1)]
    public byte[] DataCompressed
    {
        get
        {
            return this.dataCompressedField;
        }
        set
        {
            this.dataCompressedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public bool IsDataCompressed
    {
        get
        {
            return this.isDataCompressedField;
        }
        set
        {
            this.isDataCompressedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsDataCompressedSpecified
    {
        get
        {
            return this.isDataCompressedFieldSpecified;
        }
        set
        {
            this.isDataCompressedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public ArrayOfXElement Parameter
    {
        get
        {
            return this.parameterField;
        }
        set
        {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool PerformCompression
    {
        get
        {
            return this.performCompressionField;
        }
        set
        {
            this.performCompressionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PerformCompressionSpecified
    {
        get
        {
            return this.performCompressionFieldSpecified;
        }
        set
        {
            this.performCompressionFieldSpecified = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBusinessService")]
public interface IBusinessService
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBusinessService/ExecuteBusinessService", ReplyAction="http://tempuri.org/IBusinessService/ExecuteBusinessServiceResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ExceptionContext), Action="http://tempuri.org/IBusinessService/ExecuteBusinessServiceExceptionContextFault", Name="ExceptionContext", Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.IAsyncResult BeginExecuteBusinessService(ExecuteBusinessServiceRequest request, System.AsyncCallback callback, object asyncState);
    
    ExecuteBusinessServiceResponse EndExecuteBusinessService(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteBusinessService", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class ExecuteBusinessServiceRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public BusinessObject bo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public BusinessContext bizContext;
    
    public ExecuteBusinessServiceRequest()
    {
    }
    
    public ExecuteBusinessServiceRequest(BusinessObject bo, BusinessContext bizContext)
    {
        this.bo = bo;
        this.bizContext = bizContext;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteBusinessServiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class ExecuteBusinessServiceResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public BusinessObject bo;
    
    public ExecuteBusinessServiceResponse()
    {
    }
    
    public ExecuteBusinessServiceResponse(BusinessObject bo)
    {
        this.bo = bo;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBusinessServiceChannel : IBusinessService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ExecuteBusinessServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ExecuteBusinessServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public BusinessObject Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((BusinessObject)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BusinessServiceClient : System.ServiceModel.ClientBase<IBusinessService>, IBusinessService
{
    
    private BeginOperationDelegate onBeginExecuteBusinessServiceDelegate;
    
    private EndOperationDelegate onEndExecuteBusinessServiceDelegate;
    
    private System.Threading.SendOrPostCallback onExecuteBusinessServiceCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public BusinessServiceClient()
    {
    }
    
    public BusinessServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<ExecuteBusinessServiceCompletedEventArgs> ExecuteBusinessServiceCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IBusinessService.BeginExecuteBusinessService(ExecuteBusinessServiceRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginExecuteBusinessService(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private System.IAsyncResult BeginExecuteBusinessService(BusinessObject bo, BusinessContext bizContext, System.AsyncCallback callback, object asyncState)
    {
        ExecuteBusinessServiceRequest inValue = new ExecuteBusinessServiceRequest();
        inValue.bo = bo;
        inValue.bizContext = bizContext;
        return ((IBusinessService)(this)).BeginExecuteBusinessService(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteBusinessServiceResponse IBusinessService.EndExecuteBusinessService(System.IAsyncResult result)
    {
        return base.Channel.EndExecuteBusinessService(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    private BusinessObject EndExecuteBusinessService(System.IAsyncResult result)
    {
        ExecuteBusinessServiceResponse retVal = ((IBusinessService)(this)).EndExecuteBusinessService(result);
        return retVal.bo;
    }
    
    private System.IAsyncResult OnBeginExecuteBusinessService(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        BusinessObject bo = ((BusinessObject)(inValues[0]));
        BusinessContext bizContext = ((BusinessContext)(inValues[1]));
        return this.BeginExecuteBusinessService(bo, bizContext, callback, asyncState);
    }
    
    private object[] OnEndExecuteBusinessService(System.IAsyncResult result)
    {
        BusinessObject retVal = this.EndExecuteBusinessService(result);
        return new object[] {
                retVal};
    }
    
    private void OnExecuteBusinessServiceCompleted(object state)
    {
        if ((this.ExecuteBusinessServiceCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ExecuteBusinessServiceCompleted(this, new ExecuteBusinessServiceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ExecuteBusinessServiceAsync(BusinessObject bo, BusinessContext bizContext)
    {
        this.ExecuteBusinessServiceAsync(bo, bizContext, null);
    }
    
    public void ExecuteBusinessServiceAsync(BusinessObject bo, BusinessContext bizContext, object userState)
    {
        if ((this.onBeginExecuteBusinessServiceDelegate == null))
        {
            this.onBeginExecuteBusinessServiceDelegate = new BeginOperationDelegate(this.OnBeginExecuteBusinessService);
        }
        if ((this.onEndExecuteBusinessServiceDelegate == null))
        {
            this.onEndExecuteBusinessServiceDelegate = new EndOperationDelegate(this.OnEndExecuteBusinessService);
        }
        if ((this.onExecuteBusinessServiceCompletedDelegate == null))
        {
            this.onExecuteBusinessServiceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExecuteBusinessServiceCompleted);
        }
        base.InvokeAsync(this.onBeginExecuteBusinessServiceDelegate, new object[] {
                    bo,
                    bizContext}, this.onEndExecuteBusinessServiceDelegate, this.onExecuteBusinessServiceCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IBusinessService CreateChannel()
    {
        return new BusinessServiceClientChannel(this);
    }
    
    private class BusinessServiceClientChannel : ChannelBase<IBusinessService>, IBusinessService
    {
        
        public BusinessServiceClientChannel(System.ServiceModel.ClientBase<IBusinessService> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginExecuteBusinessService(ExecuteBusinessServiceRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("ExecuteBusinessService", _args, callback, asyncState);
            return _result;
        }
        
        public ExecuteBusinessServiceResponse EndExecuteBusinessService(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            ExecuteBusinessServiceResponse _result = ((ExecuteBusinessServiceResponse)(base.EndInvoke("ExecuteBusinessService", _args, result)));
            return _result;
        }
    }
}

[System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
[System.CodeDom.Compiler.GeneratedCodeAttribute("SlSvcUtil", "5.0.0.0")]
public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
{
    
    private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
    
    public ArrayOfXElement()
    {
    }
    
    public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
    {
        get
        {
            return this.nodesList;
        }
    }
    
    public virtual System.Xml.Schema.XmlSchema GetSchema()
    {
        throw new System.NotImplementedException();
    }
    
    public virtual void WriteXml(System.Xml.XmlWriter writer)
    {
        System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
        for (
        ; e.MoveNext(); 
        )
        {
            ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
        }
    }
    
    public virtual void ReadXml(System.Xml.XmlReader reader)
    {
        for (
        ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
        )
        {
            if ((reader.NodeType == System.Xml.XmlNodeType.Element))
            {
                System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                Nodes.Add(elem);
            }
            else
            {
                reader.Skip();
            }
        }
    }
}
