//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;


namespace SEMR
{

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBusinessService")]
public interface IBusinessService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/ExecuteBusinessService", ReplyAction="http://tempuri.org/IBusinessService/ExecuteBusinessServiceResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Medisys.Framework.ExceptionContext), Action="http://tempuri.org/IBusinessService/ExecuteBusinessServiceExceptionContextFault", Name="ExceptionContext", Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ExecuteBusinessServiceResponse ExecuteBusinessService(ExecuteBusinessServiceRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessService/ExecuteBusinessService", ReplyAction="http://tempuri.org/IBusinessService/ExecuteBusinessServiceResponse")]
    System.Threading.Tasks.Task<ExecuteBusinessServiceResponse> ExecuteBusinessServiceAsync(ExecuteBusinessServiceRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework.Business")]
public partial class BusinessObject
{
    
    private System.Data.DataSet dataField;
    
    private byte[] dataCompressedField;
    
    private bool isDataCompressedField;
    
    private bool isDataCompressedFieldSpecified;
    
    private System.Data.DataSet parameterField;
    
    private bool performCompressionField;
    
    private bool performCompressionFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public System.Data.DataSet Data
    {
        get
        {
            return this.dataField;
        }
        set
        {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=1)]
    public byte[] DataCompressed
    {
        get
        {
            return this.dataCompressedField;
        }
        set
        {
            this.dataCompressedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public bool IsDataCompressed
    {
        get
        {
            return this.isDataCompressedField;
        }
        set
        {
            this.isDataCompressedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsDataCompressedSpecified
    {
        get
        {
            return this.isDataCompressedFieldSpecified;
        }
        set
        {
            this.isDataCompressedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public System.Data.DataSet Parameter
    {
        get
        {
            return this.parameterField;
        }
        set
        {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool PerformCompression
    {
        get
        {
            return this.performCompressionField;
        }
        set
        {
            this.performCompressionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PerformCompressionSpecified
    {
        get
        {
            return this.performCompressionFieldSpecified;
        }
        set
        {
            this.performCompressionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework.Business")]
public partial class BusinessContext
{
    
    private string bizServiceCodeField;
    
    private bool byPassDataIntegrityCheckField;
    
    private bool byPassDataIntegrityCheckFieldSpecified;
    
    private string clientCodeField;
    
    private string institutionCodeField;
    
    private string locationIPAddressField;
    
    private string locationMachineNameField;
    
    private string loginAccountIDField;
    
    private string loginIDField;
    
    private string sessionIDField;
    
    private string transactionIDField;
    
    private string userNameField;
    
    private string userProfileIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string BizServiceCode
    {
        get
        {
            return this.bizServiceCodeField;
        }
        set
        {
            this.bizServiceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool ByPassDataIntegrityCheck
    {
        get
        {
            return this.byPassDataIntegrityCheckField;
        }
        set
        {
            this.byPassDataIntegrityCheckField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ByPassDataIntegrityCheckSpecified
    {
        get
        {
            return this.byPassDataIntegrityCheckFieldSpecified;
        }
        set
        {
            this.byPassDataIntegrityCheckFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string ClientCode
    {
        get
        {
            return this.clientCodeField;
        }
        set
        {
            this.clientCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string InstitutionCode
    {
        get
        {
            return this.institutionCodeField;
        }
        set
        {
            this.institutionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
    public string LocationIPAddress
    {
        get
        {
            return this.locationIPAddressField;
        }
        set
        {
            this.locationIPAddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
    public string LocationMachineName
    {
        get
        {
            return this.locationMachineNameField;
        }
        set
        {
            this.locationMachineNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string LoginAccountID
    {
        get
        {
            return this.loginAccountIDField;
        }
        set
        {
            this.loginAccountIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
    public string LoginID
    {
        get
        {
            return this.loginIDField;
        }
        set
        {
            this.loginIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
    public string SessionID
    {
        get
        {
            return this.sessionIDField;
        }
        set
        {
            this.sessionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
    public string TransactionID
    {
        get
        {
            return this.transactionIDField;
        }
        set
        {
            this.transactionIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
    public string UserName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string UserProfileID
    {
        get
        {
            return this.userProfileIDField;
        }
        set
        {
            this.userProfileIDField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteBusinessService", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class ExecuteBusinessServiceRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public BusinessObject bo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public BusinessContext bizContext;
    
    public ExecuteBusinessServiceRequest()
    {
    }
    
    public ExecuteBusinessServiceRequest(BusinessObject bo, BusinessContext bizContext)
    {
        this.bo = bo;
        this.bizContext = bizContext;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ExecuteBusinessServiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class ExecuteBusinessServiceResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public BusinessObject bo;
    
    public ExecuteBusinessServiceResponse()
    {
    }
    
    public ExecuteBusinessServiceResponse(BusinessObject bo)
    {
        this.bo = bo;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBusinessServiceChannel : IBusinessService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BusinessServiceClient : System.ServiceModel.ClientBase<IBusinessService>, IBusinessService
{
    
    public BusinessServiceClient()
    {
    }
    
    public BusinessServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BusinessServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BusinessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BusinessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ExecuteBusinessServiceResponse IBusinessService.ExecuteBusinessService(ExecuteBusinessServiceRequest request)
    {
        return base.Channel.ExecuteBusinessService(request);
    }
    
    public void ExecuteBusinessService(ref BusinessObject bo, BusinessContext bizContext)
    {
        ExecuteBusinessServiceRequest inValue = new ExecuteBusinessServiceRequest();
        inValue.bo = bo;
        inValue.bizContext = bizContext;
        ExecuteBusinessServiceResponse retVal = ((IBusinessService)(this)).ExecuteBusinessService(inValue);
        bo = retVal.bo;
    }
    
    public System.Threading.Tasks.Task<ExecuteBusinessServiceResponse> ExecuteBusinessServiceAsync(ExecuteBusinessServiceRequest request)
    {
        return base.Channel.ExecuteBusinessServiceAsync(request);
    }
}
namespace Medisys.Framework
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionContext", Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework")]
    public partial class ExceptionContext : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Medisys.Framework.ExceptionCategory CategoryField;
        
        private string CodeField;
        
        private string DetailField;
        
        private string IDField;
        
        private string MessageField;
        
        private string TraceField;
        
        private string TransactionIDField;
        
        private System.DateTime TriggerTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Medisys.Framework.ExceptionCategory Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail
        {
            get
            {
                return this.DetailField;
            }
            set
            {
                this.DetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Trace
        {
            get
            {
                return this.TraceField;
            }
            set
            {
                this.TraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TriggerTime
        {
            get
            {
                return this.TriggerTimeField;
            }
            set
            {
                this.TriggerTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionCategory", Namespace="http://schemas.datacontract.org/2004/07/Medisys.Framework")]
    public enum ExceptionCategory : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessError = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdentifiedException = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnidentifiedException = 2,
    }
}

}
